In [1]:
import numpy as np
from scipy.linalg import solve

In [3]:
A = [[1,0,0],[-2,1,1],[-2,-2,-1]]
b = [-1,1,2]

x = solve(A,b)
x

array([-1.,  1., -2.])

In [4]:
A = [[1,0,0],[-2,1,1],[-2,-2,-1]]
b = [0,-1,0]

x = solve(A,b)
x

array([-0.,  1., -2.])

In [5]:
A = [[1,0,0],[-2,1,1],[-2,-2,-1]]
b = [0,-1,1]

x = solve(A,b)
x

array([-0., -0., -1.])